name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (skip if not configured)
        run: |
          npm run lint --if-present

      - name: Build
        run: npm run compile

      - name: Package (optional)
        run: |
          npx vsce package || echo "Skipping vsce package if vsce not installed"
